# Generated by Django 3.0.3 on 2020-02-07 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sistema',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_sistema', models.CharField(max_length=200)),
                ('descripcion_sistema', models.CharField(max_length=300)),
                ('url_sistema', models.CharField(max_length=300)),
            ],
            options={
                'verbose_name_plural': 'Sistemas',
            },
        ),
    ]
